version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_DB: "quizdb"
      POSTGRES_USER: "quizuser"
      POSTGRES_PASSWORD: "5%6J2;ag"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - quizdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizuser -d quizdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  quizdb-data: