version: "3.9"

services:
  web:
    build:
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 127.0.0.1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "quizdb"
      POSTGRES_USER: "quizuser"
      POSTGRES_PASSWORD: "5%6J2;ag"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - quizdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  quizdb-data: